version: '3'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alexandre
      POSTGRES_PASSWORD: alexandre
    networks:
      - postgres
    volumes:
      - $HOME/docker/postgresql:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    environment:
      DEFAULT_USER: "alexandre@oracle.com"
      DEFAULT_PASSWORD: "alexandre"
    networks:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - $HOME/docker/pgadmin:/root/.pgadmin

  schema:
    image: arcanjoqueiroz/flyway:1.0.3
    command: >
      sh -c "wait-for --type postgres \
      	--host postgres \
      	--port 5432 \
      	--user test \
      	--password test \
      	--name test \
      	--seconds 20 \
      	--maxAttempts 10 && \
        flyway \
          -url=jdbc:postgresql://postgres:5432/test \
          -schemas=test \
          -user=test \
          -defaultSchema=test \
          -password=test migrate"
    volumes:
      - ./migrations:/flyway/sql
      - ./drivers:/flyway/drivers
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

